database=ASDDD
msg.lambada.1=
mainContent=These are some of the enhancement made in the Java Version 8
main.stream= 3. Java 8 Stream Sample
main.inheritance= 2. Java 8 Inheritance
main.lambda= 4. Java Lambda
main.main=1. Main Page
main.exit=0. Exit



stream.part.2a= 2a. List with filter